Insert into allsupersetting (stid,creator,typeofsetting,deadlinedate,deadlinetime)values("stid7oN70","admin","1","2024-02-04","23:00");
insert into allnotice values("nidstid7oN70","admin","Admin",now(),"1","Deadline for Submitting Sememster Timetable","The deadline of submitting semester timetable has been set as follows: newline Date: 04/02/2024 newline Time: 23:00:00 newline  newline Please be remined that to upload your timetable pic from Buniport as proof. newline Submission without valid proof will not be reviewd by Supervisor. newline  newline For Student who enrolled 0 course this sememster, should all input an entry as a declaration.");

Insert into allsupersetting (stid,creator,typeofsetting,deadlinedate,deadlinetime)values("stidGfNZu","admin","2","2024-02-04","23:00");
insert into allnotice values("nidstidGfNZu","admin","Admin",now(),"1","Deadline for Submitting Unavailable Timeslots","The deadline of submitting unavailable timeslots has been set as follows: newline Date: 04/02/2024 newline Time: 23:00:00 newline  newline Please be remined that to upload a valid proof. newline Submission without valid proof will not be reviewd by Supervisor. newline  newline Reasons like part-time job will not be approved.");

Insert into allsupersetting (stid,creator,typeofsetting,startdate,starttime,enddate,endtime)values("stid736WB","admin","3","2024-04-15","09:30","2024-04-20","18:30");
insert into allnotice values("nidstid736WB","admin","Admin",now(),"1","Presentation Period Date","The presentation period date has been set as follows: newline From : 15/04/2024 , 09:30:00 newline To   : 20/04/2024 , 18:30:00 newline  newline Students should start applying their unavaliable timeslots for the presentation period. newline Reasons like parttime job will not be acceptable. newline  newline Please be reminded that to provide valid proof to your supervisor when submitting the request, newline or else the request will not be consider.");

Insert into allsupersetting (stid,creator,typeofsetting,deadlinedate,deadlinetime)values("stidqBQSy","admin","4","2024-03-15","22:00");
insert into allnotice values("nidstidqBQSy","admin","Admin",now(),"1","Presentation Schdeule Release Date","The release date for presentation schdeule has been set as follows: newline Date: 15/03/2023 newline Time: 22:00:00 newline  newline All users can check and their personal timeslots after the release of the schdeule.");

Insert into allsupersetting (stid,creator,typeofsetting,deadlinedate,deadlinetime)values("stidfcM35","admin","5","2024-02-05","10:30");
insert into allnotice values("nidstidfcM35","admin","Admin",now(),"3","Deadline for Student List Upload","The deadline of uploading student list has been set as follows: newline Date: 05/05/2024 newline Time: 23:30:00 newline  newline  After gathering all the student list from supervisors, observer for students will be arranged.");

Insert into allsupersetting (stid,creator,typeofsetting,deadlinedate,deadlinetime)values("stidwTbry","admin","6","2024-02-04","23:15");
insert into allnotice values("nidstidwTbry","admin","Admin",now(),"3","Deadline for Upload Supervisor Preference","The deadline of uploading supervisor preference has been set as follows: newline Date: 04/02/2024 newline Time: 23:15:00 newline  newline  Please be aware that the final schdule may not be able to fullfill all supervisor's preferences.");