Delete from allpreffromsup;
Delete from supervisoravailable;
Delete from studentavailable;
Delete from allschedulebox;
Delete from manualhandlecase;
Delete from threeparty;
Delete from supervisorpairstudent;
Delete from observerpairstudent;
Delete from allrequestfromsupervisor;
Delete from allstudenttakecourse;
Delete from allrequestfromstudent;
Delete from allsupertakecourse;
Delete from alltakecourse;
Delete from student;
Delete from supervisor;
DELETE FROM allusers WHERE role != "adm";
