Update supervisor set submission = "N";
Update student set ttbsubmission = "N",ttbcomments = "";
Delete from alltakecourse;
Delete from allsupertakecourse;
Delete from allstudenttakecourse;
Delete from allclass;
Delete from supervisoravailable;
Delete from studentavailable;
Delete from allschedulebox;
Delete from manualhandlecase;
Delete from threeparty;